name: "HLSL Tests"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: "read"

jobs:
  CompileHLSL:
    name: "Compile HLSL"

    runs-on: "windows-2022"

    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Run compile-hlsl.bash"
        run: "${{ github.workspace }}\\scripts\\compile-hlsl.bash"
